export enum Emojis {
  GUCCI_REE     = '<:gucciREEE:604019562849107982>',
  GUCCI_ROAR    = '<:gucciROAR:604019561578233895>',
  GUCCI_THINK   = '<:GucciThink:628250209654145034>',
  GUCCI_PANIC   = '<:gucciPANIC:604019562811490344>',
  GUCCI_PANIC_2 = '<:gucciPANIC2:604019561993469993>',
  GUCCI_SCREAM  = '<:gucciSCREAM:604019562396254238>',
  GUCCI_SIDEEYE = '<:gucciSIDEEYE:604019561536159747>',
};

export const CatPics: string[] = [
  'https://i.imgur.com/8p3v4EL.jpg',
  'https://i.imgur.com/suZ0ACG.jpg',
  'https://i.imgur.com/fb6bhvv.jpg',
  'https://i.imgur.com/1f6iw65.jpg',
  'https://i.imgur.com/QDDrUEc.jpg',
  'https://i.imgur.com/6XkbvtM.jpg',
  'https://i.imgur.com/8oCcE5V.jpg',
  'https://i.imgur.com/uhk7ACi.jpg',
  'https://i.imgur.com/9fEhda3.jpg',
  'https://i.imgur.com/csc3JNY.jpg',
  'https://i.imgur.com/T14eIe9.jpg',
  'https://i.imgur.com/1pb8LEi.jpg',
  'https://i.imgur.com/T9vml3U.jpg',
  'https://i.imgur.com/vwndGHJ.jpg',
  'https://i.imgur.com/H7wcnca.jpg',
  'https://i.imgur.com/VxCtbZo.jpg',
  'https://i.imgur.com/LW4SojX.jpg',
  'https://i.imgur.com/4LpwE3n.jpg',
  'https://i.imgur.com/k7oCnE4.jpg',
  'https://i.imgur.com/RwQ92l5.jpg',
  'https://i.imgur.com/Eumuax5.jpg',
  'https://i.imgur.com/CGhAUS5.jpg',
  'https://i.imgur.com/pAa23QW.jpg',
  'https://i.imgur.com/iTggkic.jpg',
  'https://i.imgur.com/qf6u7u0.jpg',
  'https://i.imgur.com/j0LPvvp.jpg',
  'https://i.imgur.com/3mmxVz4.jpg',
  'https://i.imgur.com/H9FZSpY.jpg',
  'https://i.imgur.com/hPrmMWg.jpg',
  'https://i.imgur.com/puvbmzv.jpg',
  'https://i.imgur.com/uhkZZr6.jpg',
  'https://i.imgur.com/Aovtz1Z.jpg',
  'https://i.imgur.com/6fsjxMI.jpg',
  'https://i.imgur.com/gap3TtY.jpg',
  'https://i.imgur.com/GFsvIrZ.jpg',
  'https://i.imgur.com/nccr6PK.jpg',
  'https://i.imgur.com/CNPdJWd.jpg',
  'https://i.imgur.com/5kCX1uA.jpg',
  'https://i.imgur.com/dnprb6z.jpg',
  'https://i.imgur.com/dVQidha.jpg',
  'https://i.imgur.com/xtJ3Rmf.jpg',
  'https://i.imgur.com/n6VxRDH.jpg'
];